--- #YAML:1.0
name:               re-engine-Lua
version:            0.09
abstract:           Lua regular expression engine
author:
    - Francois PERRAD <francois.perrad@gadz.org>
license:            MIT
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:             5.01
    Test::Exception:  0
    Test::Warn:       0
    XSLoader:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
